### ISSUE TITLE
who's who game link points to hacktoberfest-project-ideas repo

### ISSUE THREAD

**Issue by MisterC-Rogers** [FreeCodeCampOKC/hacktoberfest-project-ideas#3]

**Comment by chris-tse** [comment]
Might be nice to fix the existing link to point to the game itself (https://whos-who.fccokc.com) and add an extra phrase at the end like "You can check out the repo here" with a link on "repo" to GitHub (https://github.com/FreeCodeCampOKC/techlahoma-whos-who)

**Comment by chris-tse** [comment]
Fixed by #5
